### PR TITLE
Fix for ExtractedText fields, contributors and maintainers 

### PR DESCRIPTION
**Pull request by ghost**
*_What's new:
*_
1. Extracted License Text - with nomos license scanner
2. Project level information - contact DoSOCSv2 organization
3. Updated copyright information
4. Updated maintainers

This merge has fix for #30 with commit `da9b964`

### CODE REVIEW

**Comment by ghost** [comment]
I am curious about this new "scanproject" command. Why add a command that is a no-op and tells you to contact DoSOCSv2 organization?

**Comment by ghost** [comment]
This merge has fix for #30 with commit  da9b964

**Comment by ghost** [comment]
@ttgurney The idea is to advertise the capability but is not currently available as part of DoSOCSv2 repo. Do you suggest there be an attempt to import project-level-info and if failure print message?

**Comment by mlinksva** [comment]
> advertise the capability but is not currently available as part of DoSOCSv2 

It's not clear to me what this capability is, so maybe the advertisement is not very successful. :smile: What is it?

It's also only suggested by usage, not --help, not the project README.

**Pull request merged**
