### PR TITLE
Fix a error as fowllowing:

### PR DESCRIPTION
**Pull request by zhengrq-fnst**
" TypeError: cannot use a string pattern on a bytes-like object"

Signed-off-by: Zheng Ruoqin <zhengrq.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by ghost** [comment]
@zhengrq-fnst curious to know a little more. Are you using Python2.7.x?

**Comment by zhengrq-fnst** [comment]
No, I'm using Python 3.5.x.

**Comment by zhengrq-fnst** [comment]
No, I'm using Python 3.5.x.

--------------------------------------------------
Zheng Ruoqin
Nanjing Fujitsu Nanda Software Tech. Co., Ltd.(FNST)
ADDR.: No.6 Wenzhu Road, Software Avenue,
       Nanjing, 210012, China
MAIL : zhengrq.fnst@cn.fujistu.com

**Comment by ghost** [comment]
DoSOCSv2 was originally written for 2.7 
`'Programming Language :: Python :: 2.7',` in `setup.py` 

This explains why you encountered a type error. I would like to run dosocsv2 in a 3.6 virtualenv for the changes you made and see if I can verify that this code works flawlessly in 3.x.  The original author Tom Gurney had envisioned use of python3. Python2.7 is dying and I think it is time to ensure this will be future proof

**Comment by zhengrq-fnst** [comment]
Well, Do you have the plan to change from python2 to python3?

Now, I have a patch to fix magic error, but it can’t pass your CI test as the test is in the environment of Python 2.7.14.


--------------------------------------------------
Zheng Ruoqin
Nanjing Fujitsu Nanda Software Tech. Co., Ltd.(FNST)
ADDR.: No.6 Wenzhu Road, Software Avenue,
       Nanjing, 210012, China
MAIL : zhengrq.fnst@cn.fujistu.com

**Pull request closed without merging**
