### PR TITLE
Upgrade SHA-1 to SHA-256

### PR DESCRIPTION
**Pull request by tpflueger**
Upgraded to use SHA-256. Not exactly sure what the intended goal of creating the unique uuid so I just updated it to include at minimum 60 characters for the intended 64 character key.

### CODE REVIEW

**Comment by ghost** [comment]
@tpflueger 
1. In the file `dosocs2/util.py`, The function `gen_id_string` generates universal unique identifier.

`new_file_name = file_name_for_id(file_name or uuid4[19:23])`
`pieces = 'SPDXRef', prefix, new_file_name, suffix`
`return '-'.join(pieces)`

One Instance (Against GNU Time 1.7) :
`SPDXRef-file-AUTHORS-0073-2c22544f`
`SPDXRef-file-ChangeLog-345e-98b44c1b`

The intended purpose is to uniquely identify a file or a package. This requirement is part of the SPDX 2,0 Specification. (2.5 SPDX Document Namespace )
1. I currently see that you are generating SHA256 and return generated 64 character hexdigest as is. That is the correct implementation for SHA256. If you are referring to UUID and that you are returning more characters for inclusion, as part of UUID, a longer string is generated. 

I hope this clarifies.

**Comment by tpflueger** [comment]
@UShan89 
Yeah that clarifies it, I was just wondering if it mattered if duplicate sections of the uuid4 being used to create the unique identifier would cause a problem.

**Comment by ghost** [comment]
Nope, none that I am aware of.

**Comment by tpflueger** [comment]
I completely forgot but noticed I created pull request for master. Would you want me to change and use develop or would this be alright?

**Comment by ghost** [comment]
@tpflueger  sure that would be great. I will close this pull request for now.

**Pull request closed without merging**
